# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn_title', models.CharField(max_length=250)),
                ('inn_detail', models.CharField(blank=True, max_length=100000)),
                ('inn_detail1', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Innovator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('inn_location', models.CharField(max_length=250)),
                ('inn_pic', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='innovation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Innovator'),
        ),
    ]
