# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='person',
        ),
        migrations.AddField(
            model_name='innovation',
            name='inn_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Innovator',
        ),
    ]
