# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170530_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='inn_detail1',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='inn_image',
            field=models.FileField(upload_to=''),
        ),
    ]
