# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170530_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='inn_image',
            field=models.FileField(blank=True, default='static/home/images/hbnlogo.png', upload_to=''),
        ),
    ]
