# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20170530_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='inn_image',
            field=models.FileField(default='settings.MEDIA_ROOT/media/hbnlogo.png', upload_to=''),
        ),
    ]
