# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170530_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='inn_detail1',
        ),
        migrations.AddField(
            model_name='innovation',
            name='inn_brief',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='inn_detail',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='inn_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
