# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170530_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_title', models.CharField(max_length=100)),
                ('act_logo', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
