# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='innovator',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
