# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_innovation_innovator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='inn_detail',
            field=models.TextField(),
        ),
    ]
