# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20170531_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='inn_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='inn_detail',
            field=models.TextField(blank=True),
        ),
    ]
