# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20170531_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='inn_brief',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
