# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170531_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_brief',
            new_name='innovation_brief',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_detail',
            new_name='innovation_detail',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_file',
            new_name='innovation_file',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_image',
            new_name='innovation_image',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_title',
            new_name='innovation_title',
        ),
    ]
