# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 06:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170531_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_brief',
            new_name='brief',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_detail',
            new_name='detail',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='innovation',
            old_name='inn_title',
            new_name='title',
        ),
    ]
