# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20170531_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='brief',
            field=models.CharField(max_length=100),
        ),
    ]
