# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20170531_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovation',
            name='image',
            field=models.FileField(default='hbnlogo.png', upload_to=''),
        ),
    ]
