# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20170531_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='innovation',
            name='updatedtime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
