# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_announcement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='head',
            field=models.BooleanField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
