# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_announcement_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='head',
        ),
    ]
