# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_remove_announcement_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='head',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
