# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_announcement_head'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]
