# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-05 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_auto_20170601_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='act_brief',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
