# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 11:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_auto_20170605_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='innovation',
            options={'ordering': ['-updatedtime', '-timestamp']},
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='brief',
        ),
    ]
