# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 11:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_auto_20170605_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='Location',
            field=models.CharField(default=datetime.datetime(2017, 6, 5, 11, 43, 56, 602169, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
