# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 12:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20170605_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='act_brief',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='act_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 6, 5, 12, 39, 15, 728111, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='act_logo',
            field=models.FileField(blank=True, default='hbnlogo.png', upload_to=''),
        ),
    ]
