# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_auto_20170605_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activities',
            name='act_brief',
        ),
        migrations.AddField(
            model_name='activities',
            name='act_url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
