# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_auto_20170605_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='back',
            field=models.FileField(default=datetime.datetime(2017, 6, 5, 19, 5, 25, 457369, tzinfo=utc), upload_to=''),
            preserve_default=False,
        ),
    ]
