# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_activities_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='act_timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
