# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-05 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20170606_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='act_timestamp',
            field=models.DateField(),
        ),
    ]
