# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Members',
        ),
    ]
