# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-06 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20170606_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Network_Members',
        ),
    ]
