# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 05:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_delete_networkmembers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='location',
        ),
    ]
