# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 05:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_remove_innovation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='location',
            field=models.CharField(default=datetime.datetime(2017, 6, 7, 5, 26, 3, 457864, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
