# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20170607_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('posted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
