# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_delete_suggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('posted_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='innovation',
            name='tag',
            field=models.CharField(blank=True, default='guest', max_length=50),
        ),
    ]
