# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20170607_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='innovation',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='image',
            field=models.ImageField(default='hbnlogo.png', height_field='height_field', upload_to=home.models.upload_location, width_field='width_field'),
        ),
    ]
