# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_auto_20170608_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovator_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='hbnlogo.png', height_field='height_field', upload_to=home.models.upload_location, width_field='width_field')),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
    ]
