# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 07:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_auto_20170608_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InnovationOfDay',
        ),
        migrations.AddField(
            model_name='announcement',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(default='hbnlogo.png', height_field='height_field', upload_to=home.models.upload_location, width_field='width_field'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='inn_detail',
            field=models.TextField(default=datetime.datetime(2017, 6, 8, 7, 47, 45, 470511, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='inn_location',
            field=models.CharField(default=datetime.datetime(2017, 6, 8, 7, 47, 50, 547255, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='innovator_name',
            field=models.CharField(default=datetime.datetime(2017, 6, 8, 7, 47, 52, 908956, tzinfo=utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='mark_inn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
