# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_auto_20170608_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='inn_detail',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='inn_location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='innovator_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
