# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_auto_20170608_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
