# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 08:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_auto_20170608_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='InnovationOfDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovator_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('detail', models.TextField()),
                ('image', models.ImageField(default='hbnlogo.png', height_field='height_field', upload_to=home.models.upload_location, width_field='width_field')),
                ('mark', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='image',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='inn_detail',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='inn_location',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='innovator_name',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='mark_inn',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 8, 8, 32, 59, 396911, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
