# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20170608_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationofday',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='innovationofday',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
