# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0066_auto_20170608_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationofday',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 6, 8, 9, 1, 11, 299471, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
