# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0067_innovationofday_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationofday',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
