# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0068_auto_20170608_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetProf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
