# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0069_meetprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetprof',
            name='prof_name',
            field=models.CharField(default=datetime.datetime(2017, 6, 8, 10, 44, 53, 413112, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
