# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-08 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0071_frontimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontimage',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 6, 8, 16, 2, 40, 735945, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
    ]
