# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-09 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0072_frontimage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frontimage',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
